perform_tests: &PERFORM_TESTS
  test_script:
    set -x
    cd test
    PYVERSION=$(./py --version)
    ./py test-rec.py -o "test-rec-macos-$PYVERSION.wav"
    ./py test-dependencies.py
    ./py test-notation.py -o "test-notation-macos-$PYVERSION.pdf"
    cp *.wav ../artifacts
    cp *.pdf ../artifacts
    rm py

setup_macos: &SETUP_MACOS
  setup_macos_script: |
    set -x
    curl -L -o csound6.18.dmg https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg
    brew install p7zip
    7z x csound6.18.dmg
    cd Csound-universal-6.18.1
    sudo installer -pkg csound-MacOS-universal-6.18.1.pkg -target /
    csound --version
    mkdir -p artifacts

test_git_310_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  <<: *SETUP_MACOS

  test_macos_arm64_python310_git_script: |
    brew install python@3.10
    ln -s $(which python3.10) py
    ./py -m pip install .
  <<: *PERFORM_TESTS

test_git_311_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  <<: *SETUP_MACOS

  test_macos_arm64_python310_git_script: |
    brew install python@3.11
    ln -s $(which python3.11) py
    ./py -m pip install .
  <<: *PERFORM_TESTS

test_pip_310_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  <<: *SETUP_MACOS

  test_macos_arm64_python310_git_script: |
    brew install python@3.10
    ln -s $(which python3.10) py
    ./py -m pip install maelzel
  <<: *PERFORM_TESTS

test_pip_311_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  <<: *SETUP_MACOS

  test_macos_arm64_python310_git_script: |
    brew install python@3.11
    ln -s $(which python3.11) py
    ./py -m pip install maelzel

  <<: *PERFORM_TESTS

