
setup_macos: &SETUP_MACOS
  setup_script: |
    curl -L -o csound6.18.dmg https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg
    brew install p7zip
    brew install lilypond
    7z x csound6.18.dmg
    sudo installer -pkg Csound-universal-6.18.1/csound-MacOS-universal-6.18.1.pkg -target /
    csound --version
    brew install python@$PYVERSION
    ls -l
    python$PYVERSION --version
    python$PYVERSION -m venv .venv
    source .venv/bin/activate
    python --version
    if  [[ "$METHOD" == "pip" ]]; then
      python -m pip install maelzel
    else
      python -m pip install .
    fi


perform_tests: &PERFORM_TESTS
  main_test_script: |
    set -x
    python3 -m venv .venv
    source .venv/bin/activate
    python --version
    mkdir -p artifacts
    cd test
    python test-rec.py -o "test-rec-macos-$PYVERSION-$METHOD.wav"
    python test-dependencies.py
    python test-notation.py -o "test-notation-macos-$PYVERSION-$METHOD.pdf"
    ls -l 
    cp *.wav ../artifacts
    cp *.pdf ../artifacts
    cd ..

    ls -l
    ls -l artifacts/*

  test_artifacts:
    path: artifacts/*

   
test_git_309_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  environment:
    PYVERSION: 3.9
    METHOD: git

  <<: *SETUP_MACOS

  <<: *PERFORM_TESTS
  
  
test_git_311_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  environment:
    METHOD: git
    PYVERSION: 3.11

  <<: *SETUP_MACOS

  <<: *PERFORM_TESTS

test_pip_309_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  environment:
    METHOD: pip
    PYVERSION: 3.9

  <<: *SETUP_MACOS

  <<: *PERFORM_TESTS


test_pip_311_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  environment:
    METHOD: pip
    PYVERSION: 3.11

  <<: *SETUP_MACOS

  <<: *PERFORM_TESTS

