perform_tests: &PERFORM_TESTS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  main_test_script: |
    set -x
    ./py --version
    echo "ID: '$ID'"
    cd test
    ../py test-rec.py -o "test-rec-macos-$ID.wav"
    ../py test-dependencies.py
    ../py test-notation.py -o "test-notation-macos-$ID.pdf"
    cp *.wav ../artifacts
    cp *.pdf ../artifacts

  test_artifacts:
    path: artifacts/*


setup_macos: &SETUP_MACOS
  setup_script: |
    curl -L -o csound6.18.dmg https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg
    brew install p7zip
    7z x csound6.18.dmg
    cd Csound-universal-6.18.1
    sudo installer -pkg csound-MacOS-universal-6.18.1.pkg -target /
    csound --version
    mkdir -p artifacts

test_git_310_task:
  environment:
    ID: git-310
  <<: *SETUP_MACOS
  install_script: |
    brew install python@3.10
    ln -s $(which python3.10) py
    ./py -m pip install .
  <<: *PERFORM_TESTS

test_git_311_task:
  environment:
    ID: git-311
  <<: *SETUP_MACOS
  install_script: |
    brew install python@3.11
    ln -s $(which python3.11) py
    ./py -m pip install .
  <<: *PERFORM_TESTS

test_pip_310_task:
  environment:
    ID: pip-310
  <<: *SETUP_MACOS
  install_script: |
    brew install python@3.10
    ln -s $(which python3.10) py
    ./py -m pip install maelzel
  <<: *PERFORM_TESTS

test_pip_311_task:
  environment:
    ID: pip-311
  <<: *SETUP_MACOS
  install_script: |
    brew install python@3.11
    ln -s $(which python3.11) py
    ./py -m pip install maelzel
  <<: *PERFORM_TESTS

