import struct

def timid_get_info(path):
    """
    get information about .timid files generated by timbreID 
    returns a tuplet (number-of-templates, feature-length-of-each-template)
    """
    f = open(path, 'rb')
    numtemplates, feature_length = f.read(4), f.read(4)  
    numtemplates = struct.unpack("l", numtemplates)[0]
    feature_length = struct.unpack("l", feature_length)[0]
    return numtemplates, feature_length

