on: [push]

jobs:
  test:
    name: Test maelzel in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: macos - setup
        if: runner.os == 'macos'
        run: |
          set -x
          curl -L -o csound6.18.dmg https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg
          brew install p7zip
          7z x csound6.18.dmg
          cd Csound-universal-6.18.1
          sudo installer -pkg csound-MacOS-universal-6.18.1.pkg -target /
          csound --version
          cd ..

      - name: macos - test install from pypi
        if: runner.os == 'macos'
        run: |
          set -x
          python -m venv maelzelenv
          source maelzelenv/bin/activate
          pip install maelzel
          mkdir -p artifacts

          cd test
          python test-rec.py
          cp *.wav ../artifacts
          cd ..
          deactivate

      - name: macos - test install from git
        if: runner.os == 'macos'
        run: |
          set -x
          pip install .
          mkdir -p artifacts
          
          cd test
          python test-rec.py
          cp *.wav ../artifacts
          cd ..
          pip uninstall -y maelzel


      - uses: actions/upload-artifact@v3
        with:
          path: artifacts
